nikhilbadyal/docker-py-revanced

- .pre-commit-config.yaml
✨Update versions of tools in pre-commit configs to latest version
> ⬆️Update pre-commit hooks

- README.md
check readme about the manual to configure telegram bot
> Updated Readme about telegram bot

- README.md
- src/config.py
- src/patches.py
Removed [anytracker](https://github.com/revanced/revanced-patches/pull/1094) Patch
> Removed TickTick App

- README.md
- src/config.py
- src/patches.py
Reverts nikhilbadyal/docker-py-revanced#82
> Revert "Removed TickTick App"

- .github/workflows/build-apk.yml
Just changing mgaisk to magisk 😄
> fix typo in build-apk.yml

- src/downloader.py
> ✨ Patch ytmusic-arm64

- README.md
- src/config.py
- src/downloader.py
> Ability to provide apk manually.

- src/patches.py
Related to https://github.com/nikhilbadyal/docker-py-revanced/issues/198 .
I honestly have almost zero experience of coding so this is a completely ameterish attempt of pull request, if this doesn't actually fix things, my apologies in advance.
> Fix Revanced Extended App IDs

- src/config.py
GPLAY: https://play.google.com/store/apps/details?id=com.twitter.android
APKM: https://www.apkmirror.com/apk/x-corp/twitter/
Older apkm links do work but created this PR in regards with future changes.
> Twitter rebranded to X

- README.md
> Fix Messenger app name and URL

- .github/workflows/pr-checks.yml
- src/downloader/apkmirror.py
[Closes  295](https://github.com/nikhilbadyal/docker-py-revanced/issues/295)
> 🐛 Wrong version selection in APKMirror

- README.md
> Clean docs

- .gitignore
- src/parser.py
Discussed [here](https://github.com/nikhilbadyal/docker-py-revanced/discussions/323)
> 🐛 Handle new v3 cli args

- README.md
Just corrected the path for microg
> Update README.md for microg path

- main.py
> 🐛 Added missing call to extra downloads

- .github/workflows/build-apk.yml
> ✨ Expect Apprise notify in workflow run

- src/parser.py
- src/patches.py
> 🐞 Updated inclusion logic

- .env.my
- README.md
- src/downloader/github.py
> ✨ Ability to use pre-release on GitHub

- src/downloader/apkmirror.py
> ✨ Added version in output file

- .pre-commit-config.yaml
- requirements.txt
- src/app.py
> ✨ Added date in output file

- src/downloader/apkmirror.py
It'll help immensely by postponing the cloudflare 429 stoppage.
Also, I wrote down a browser (driverless) impl. Would you like to have something like that? It's fast and fully bypasses cloudflare.
> Extract source instead to reuse in extracting divs

- .github/workflows/build-artifact.yml
- README.md
> 💥 Replace docker-compose with docker compose

- .github/workflows/build-apk.yml
- .github/workflows/build-artifact.yml
- README.md
- requirements.txt
- scripts/prefered_apps.py
enhancement
___
- Added functionality to override patch apps directly from the GitHub UI, enhancing the flexibility of the build process.
- Implemented a new Python script `prefered_apps.py` to update the `PATCH_APPS` environment variable based on `PREFERRED_PATCH_APPS`.
- Updated GitHub Actions workflows (`build-apk.yml` and `build-artifact.yml`) to support the new `PREFERRED_PATCH_APPS` input.
- Documented the new override feature in `README.md`.
- Updated `requirements.txt` to include `python-dotenv` for environment variable management.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>prefered_apps.py</strong><dd><code>Add Script to Update Preferred Patch …
> ✨ Ability to override patch apps from GH UI

- .github/workflows/auto-release.yml
- .github/workflows/build-apk.yml
- check_resource_updates.py
enhancement
___
- Introduced a mechanism to dynamically determine and list apps that need repatching, optimizing the build process.
- Simplified and enhanced GitHub Actions workflows to support dynamic repatching based on the apps identified by the `check_resource_updates.py` script.
- Added support for specifying which apps to patch directly in the build workflow, allowing for more flexible build configurations.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>check_resource_updates.py</strong><dd><code>Optimize Repatch Logic for Specific Apps</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Filter to be patched

- .github/workflows/build-artifact.yml
- main.py
- src/manager/github.py
- src/utils.py
enhancement
___
- Enhanced the main application flow in `main.py` to handle updates information, including loading and saving updates data.
- Updated `GitHubManager` in `src/manager/github.py` to dynamically construct the URL for the updates file based on environment variables.
- Improved utility functions in `src/utils.py` to support dynamic updates file URL construction, loading older updates, and handling updates info during patch information saving.
- Modified GitHub Actions workflow in `.github/workflows/build-artifact.yml` to include `GITHUB_REPOSITORY` as an environment variable for builds.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details> …
> ✨ Use updates json from other branch

- check_resource_updates.py
- src/manager/github.py
- src/manager/release_manager.py
- src/utils.py
enhancement
___
- Added functionality to check for changes in the source of integrations and patches, enhancing the build trigger process.
- Implemented a new method in `GitHubManager` to fetch the last version source, supporting the new build trigger checks.
- Updated the `should_trigger_build` method in `ReleaseManager` to consider source changes, improving the accuracy of build triggers.
- Introduced new utility keys to manage resource download links and dumps, facilitating better resource management.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>check_resource_updates.py</strong><dd><code>Enhance build trigger checks with source versioning</code>&nbsp; …
> ✨ Run builder when source is changed.

- .github/workflows/dockerhub-base.yml
- .github/workflows/dockerhub.yml
- Dockerfile
- README.md
- docker-compose.yml
Reverts nikhilbadyal/docker-py-revanced#517
closes #516
> Revert "Docker Build Failing"

- README.md
- src/downloader/sources.py
- src/patches.py
Fixes - https://github.com/nikhilbadyal/docker-py-revanced/issues/548
___
enhancement
___
- Added support for Google Photos by including it in the package mapping dictionary.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>patches.py</strong><dd><code>Add Google Photos to package mapping</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/patches.py
<li>Added a new entry for Google Photos in the package mapping dictionary.<br> <br>
</details>
</td>
<td><a href="https://github.com/nikhilbadyal/docker-py-revanced/pull/549/files#diff-d185121a …
> Added google photos

- src/downloader/uptodown.py
Uptodown app download page just had an attribute name change. This PR fixes the issue with specific version downloader.
___
Bug fix
___
- Fixed a bug in the Uptodown download page parser by updating the attribute name from `code` to `data-code`.
- Ensured the specific version downloader works correctly after the Uptodown page update.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>uptodown.py</strong><dd><code>Fix attribute name change in Uptodown parser</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/downloader/uptodown.py
<li>Updated attribute name from <code>code</code> to …
> 🐛 Fix Uptodown download page parser

- README.md
documentation
___
- Corrected the title of the 'willhaben' link in the README file to accurately reflect the linked content.
- Improved the accuracy of the documentation by fixing a mistitled link.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Corrected mistitled link in README documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Corrected the title of the 'willhaben' link.<br> <li> Fixed a mistitled link in the documentation.<br>
</details>
</td>
<td><a href="https://github.com/nikhilbadyal/docker-py-revanced/pull/592/files#diff-b335630551682c19a781afebcf4d07bf978fb1 …
> willhaben link mistitled
